blank_issues_enabled: false

contact_links:
  - name: "GitHub Discussions"
    url: "https://github.com/syncfusion/maui-toolkit/discussions"
    about: "Use Syncfusion MAUI Toolkit Discussions for general inquiries"